# Unity app
env: "MiniGridNoLimit-Empty-6x6-v0"

# Operations
# Available operations: manual, train, evaluate
operations: "train"
model_path: "latest_model.pth"

# Algorithm parameters
enable_stats: False
render: False
threads: 1
save_policy_every_x_episodes: 50

# Environment parameters
action_dim: 3
vector_observation_dim: 3
image_width: 7
image_height: 7

# Memory
memory_samples: 200

# Reward
# stop training if episode_reward > solved_reward
solved_reward: 500

# Training length
# max training episodes
max_episodes: 100000
# max timesteps in one episode
max_timesteps: 500

# Model parameters
# number of variables in hidden layer
n_latent_var: 5
lr: 0.002
betas_start: 0.9
betas_end: 0.999
# discount factor
gamma: 0.99
# update policy for K epochs
K_epochs: 3
# clip parameter for PPO
eps_clip: 0.2
random_seed: 1000
