default:
    trainer: sac
    batch_size: 128
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_update: 1
    train_interval: 1
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

Pyramids:
    summary_freq: 2000
    time_horizon: 128
    batch_size: 128
    buffer_init_steps: 10000
    buffer_size: 500000
    hidden_units: 256
    num_layers: 2
    init_entcoef: 0.01
    max_steps: 5.0e5
    sequence_length: 16
    tau: 0.01
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 2.0
            gamma: 0.99
        gail:
            strength: 0.02
            gamma: 0.99
            encoding_size: 128
            use_actions: true
            demo_path: demos/ExpertPyramid.demo

VisualPyramids:
    time_horizon: 128
    batch_size: 64
    hidden_units: 256
    buffer_init_steps: 1000
    num_layers: 1
    max_steps: 5.0e5
    buffer_size: 500000
    init_entcoef: 0.01
    tau: 0.01
    reward_signals:
        extrinsic:
            strength: 2.0
            gamma: 0.99
        gail:
            strength: 0.02
            gamma: 0.99
            encoding_size: 128
            use_actions: true
            demo_path: demos/ExpertPyramid.demo
